server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LiveDemo
    username: root
    password: admin100pswd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    user:
      name: client
      password: password
